name: Deploy Dev

on:
  push:
    branches: [main]
    paths:
      - "platform/**"
      - "services/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy dev environment."

